// Auto-generated by scripts/fetch-logos.mjs — do not edit by hand.
// Maps each beer name to its local logo file. Loaded by index.html before
// script.js so logos render synchronously from the repo.
//
// Run `node scripts/fetch-logos.mjs` to populate this from Brandfetch + the
// fallback chain. Until that runs, the runtime Brandfetch chain in script.js
// still serves every logo.
window.LOCAL_LOGOS_MANIFEST = {};
